{
 "title": "AI-Stack",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"prometheus.scrape.node_exporter_metrics_aistack\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"prometheus.scrape.node_exporter_metrics_aistack\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"prometheus.scrape.node_exporter_metrics_aistack\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"prometheus.scrape.node_exporter_metrics_aistack\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  node_memory_MemTotal_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\"}\r\n  - node_memory_MemFree_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\"}\r\n  - node_memory_Buffers_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\"}\r\n  - node_memory_Cached_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\"}\r\n)",
     "legendFormat": "Used"
    },
    {
     "expr": "(\r\n  node_memory_Buffers_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\"}\r\n  + node_memory_Cached_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\"}\r\n)",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alloy_resources_machine_rx_bytes_total{job=\"prometheus.scrape.alloy_metrics_aistack\"}",
     "legendFormat": "RX"
    },
    {
     "expr": "alloy_resources_machine_tx_bytes_total{job=\"prometheus.scrape.alloy_metrics_aistack\"}",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", job=\"prometheus.scrape.node_exporter_metrics_aistack\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"prometheus.scrape.node_exporter_metrics_aistack\", instance=\"node-exporter:9100\", mode=\"idle\"}[5m]) * 100)",
     "legendFormat": "CPU {{cpu}} Usage"
    }
   ]
  }
 ]
}