{
 "title": "Plex",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"prometheus.scrape.node_exporter_metrics_plex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"prometheus.scrape.node_exporter_metrics_plex\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"prometheus.scrape.node_exporter_metrics_plex\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"prometheus.scrape.node_exporter_metrics_plex\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Plex CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", job=\"prometheus.scrape.node_exporter_metrics_plex\"}[5m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"prometheus.scrape.node_exporter_metrics_plex\", mode=\"idle\"}[5m]) * 100)\r\n",
     "legendFormat": "CPU {{cpu}} Usage"
    }
   ]
  },
  {
   "title": "Network Traffic Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alloy_resources_machine_rx_bytes_total{job=\"prometheus.scrape.alloy_metrics_plex\"}\r\n\r\n\r\n",
     "legendFormat": "RX"
    },
    {
     "expr": "alloy_resources_machine_tx_bytes_total{job=\"prometheus.scrape.alloy_metrics_plex\"}\r\n",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Network Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"prometheus.scrape.node_exporter_metrics_plex\", device=\"ens18\"}[5m]) * 8",
     "legendFormat": "{{device}} RX"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"prometheus.scrape.node_exporter_metrics_plex\", device=\"ens18\"}[5m]) * 8",
     "legendFormat": "{{device}} TX"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  node_memory_MemTotal_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}\r\n  - node_memory_MemFree_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}\r\n  - node_memory_Buffers_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}\r\n  - node_memory_Cached_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}\r\n)",
     "legendFormat": "Used"
    },
    {
     "expr": "(\r\n  node_memory_Buffers_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}\r\n  + node_memory_Cached_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}\r\n)",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"prometheus.scrape.node_exporter_metrics_plex\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_seconds_total{job=\"prometheus.scrape.node_exporter_metrics_plex\", device=\"sda\"}[5m])) * 100\r\n",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "(rate(node_disk_io_time_seconds_total{job=\"prometheus.scrape.node_exporter_metrics_plex\", device=\"sdb\"}[5m])) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_filesystem_avail_bytes{\r\n      job=\"prometheus.scrape.node_exporter_metrics_plex\",\r\n      fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\", fstype!=\"overlay\", fstype!=\"tracefs\", fstype!=\"cgroup\", fstype!=\"fuse.lxcfs\", fstype!=\"fusectl\", fstype!=\"autofs\",\r\n      mountpoint!~\"^/dev/.*|^/sys/.*|^/proc/.*|^/run/.*|^/var/lib/(docker|containerd|kubelet)/.+$|^/snap/.*|^/var/lib/docker/overlay2/.*\"\r\n    }\r\n  /\r\n    node_filesystem_size_bytes{\r\n      job=\"prometheus.scrape.node_exporter_metrics_plex\",\r\n      fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\", fstype!=\"overlay\", fstype!=\"tracefs\", fstype!=\"cgroup\", fstype!=\"fuse.lxcfs\", fstype!=\"fusectl\", fstype!=\"autofs\",\r\n      mountpoint!~\"^/dev/.*|^/sys/.*|^/proc/.*|^/run/.*|^/var/lib/(docker|containerd|kubelet)/.+$|^/snap/.*|^/var/lib/docker/overlay2/.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "Mount - {{mountpoint}}"
    }
   ]
  }
 ]
}