services:
  loki:
    image: grafana/loki:main-cb0cbb0
    container_name: loki
    ports:
      - "3200:3200"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - /mnt/monitoring/loki_data:/lokils 
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    external: true