services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3200:3200" # Standard Loki port
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

networks:
  monitoring:
    external: true