# loki-config.yaml (Recommended Modern Fix)
auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# --- THIS SECTION IS UPDATED ---
schema_config:
  configs:
    - from: 2024-04-01       # Use a recent date
      store: tsdb              # Use the modern TSDB index
      object_store: filesystem
      schema: v13              # Use a schema that supports the new features
      index:
        prefix: index_
        period: 24h

# The old `storage_config` for boltdb-shipper is no longer needed.
# TSDB uses the paths defined in the `common` block above.
storage_config:
  filesystem:
    directory: /loki/tsdb


# --- THIS SECTION IS NOW VALID ---
limits_config:
  allow_structured_metadata: true # This feature now works correctly
  retention_period: 336h