# loki-config.yaml (Quick Fix)
auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper  # Keeping the old engine
      object_store: filesystem
      schema: v11            # Keeping the old schema
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h

limits_config:
  # This is the only change. Disable the feature causing the conflict.
  allow_structured_metadata: false 
  retention_period: 336h