services:
  # NGINX Reverse Proxy Service
  nginx:
    image: nginx:latest
    container_name: my-nginx-proxy
    ports:
      # Map host ports to container ports
      - "80:80"
      - "443:443"
    volumes:
      # Mount our NGINX config
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # Mount our self-signed certificates
      - ./certs:/etc/nginx/ssl
    restart: unless-stopped

networks:
  monitoring:
    external: true