receivers:
  otlp:
    protocol: http
    host: 0.0.0.0
    port: 55678

exporters:
  jaeger:
    endpoint: jaeger:14268
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]