# StackUI
version: '3'
services:
    webapp:
      build: .
      ports:
        - "3000:3000" # Maps host port 3000 → container port 3000
      restart: unless-stopped
      environment:
        - NODE_ENV=production

networks:
  dockernet:
    external: true